// Maps each of the 79 real, individually-segmented BodyParts3D mesh names
// (source: data/Postnatal_anatomical_structure, "heart5.0i" module) onto the
// clickable structureId used by the app. Several real mesh pieces make up
// one clickable structure (e.g. five separate wall segments = one
// "leftVentricle"), exactly the way the real heart's continuous myocardium
// is one structure built of several named anatomical walls.
export const CANONICAL_TO_STRUCTURE = {
  "Anterior atrial branch of right coronary artery": "coronaryArteries",
  "Anterior cardiac vein": "coronaryVeins",
  "Anterior cusp of aortic valve": "aorticValve",
  "Anterior internodal tract": "conductionSystem",
  "Anterior leaflet of tricuspid valve": "tricuspidValve",
  "Anterior papillary muscle of left ventricle": "papillaryMusclesLV",
  "Anterior septal branch of anterior interventricular artery": "coronaryArteries",
  "Anterior wall of left ventricle": "leftVentricle",
  "Anterior wall proper of left atrium": "leftAtrium",
  "Anterior wall proper of right atrium": "rightAtrium",
  "Anulus proper of tricuspid valve": "tricuspidValve",
  "Ascending aorta proper": "ascendingAorta",
  "Atrioventricular bundle": "conductionSystem",
  "Atrioventricular node": "conductionSystem",
  "Atrioventricular node branch of right coronary artery": "coronaryArteries",
  "Atrioventricular septum": "atrioventricularSeptum",
  "Coronary sinus": "coronaryVeins",
  "Crista terminalis": "rightAtrium",
  "Diagonal branch of anterior descending branch of left coronary artery": "coronaryArteries",
  "Fibrous ring of aortic valve": "aorticValve",
  "Fibrous ring of mitral valve": "mitralValve",
  "First anterior ventricular branch of right coronary artery": "coronaryArteries",
  "First posterior ventricular branch of circumflex coronary artery": "coronaryArteries",
  "First posterior ventricular branch of right coronary artery": "coronaryArteries",
  "Free wall of left ventricle": "leftVentricle",
  "Great cardiac vein": "coronaryVeins",
  "Inferior wall of left ventricle": "leftVentricle",
  "Interatrial septum": "interatrialSeptum",
  "Lateral wall of left atrium": "leftAtrium",
  "Lateral wall of left ventricle": "leftVentricle",
  "Lateral wall proper of right atrium": "rightAtrium",
  "Left anterior cusp of pulmonary valve": "pulmonaryValve",
  "Left anterior semilunar fibrous scallop of pulmonary valve anulus": "pulmonaryValve",
  "Left marginal artery": "coronaryArteries",
  "Left posterior semilunar fibrous scallop of aortic valve anulus": "aorticValve",
  "Marginal branch of right coronary artery": "coronaryArteries",
  "Membranous part of interventricular septum proper": "interventricularSeptum",
  "Middle cardiac vein": "coronaryVeins",
  "Middle internodal tract": "conductionSystem",
  "Mural limb of supraventricular crest": "rightVentricle",
  "Muscular part of interventricular septum": "interventricularSeptum",
  "Pectinate muscle of right auricle": "rightAuricle",
  "Posterior cusp of pulmonary valve": "pulmonaryValve",
  "Posterior leaflet of tricuspid valve": "tricuspidValve",
  "Posterior semilunar fibrous scallop of pulmonary valve anulus": "pulmonaryValve",
  "Posterior vein of left ventricle": "coronaryVeins",
  "Posterior wall of left atrium": "leftAtrium",
  "Pulmonary trunk proper": "pulmonaryTrunk",
  "Right anterior cusp of pulmonary valve": "pulmonaryValve",
  "Right anterior semilunar fibrous scallop of pulmonary valve anulus": "pulmonaryValve",
  "Right fibrous trigone of heart": "interventricularSeptum",
  "Right marginal vein": "coronaryVeins",
  "Right posterior semilunar fibrous scallop of aortic valve anulus": "aorticValve",
  "Second left anterior branch of anterior interventricular branch of left coronary artery": "coronaryArteries",
  "Septal division of left branch of atrioventricular bundle": "conductionSystem",
  "Septal leaflet of tricuspid valve": "tricuspidValve",
  "Septal limb of supraventricular crest": "rightVentricle",
  "Septal papillary muscle of right ventricle": "papillaryMusclesRV",
  "Septal wall of left atrium": "leftAtrium",
  "Septal wall of left ventricle": "leftVentricle",
  "Septal wall of right atrium": "rightAtrium",
  "Septomarginal trabecula": "trabeculaeCarneae",
  "Stem of left coronary artery": "coronaryArteries",
  "Superior wall of left atrium": "leftAtrium",
  "Tendon of Todaro": "conductionSystem",
  "Third left anterior branch of anterior interventricular branch of left coronary artery": "coronaryArteries",
  "Trabecula carnea of right ventricle": "trabeculaeCarneae",
  "Triangle of sinu-atrial node": "conductionSystem",
  "Trunk of anterior interventricular branch of left coronary artery": "coronaryArteries",
  "Trunk of circumflex branch of left coronary artery": "coronaryArteries",
  "Trunk of posterior interventricular branch of left coronary artery": "coronaryArteries",
  "Trunk of right coronary artery": "coronaryArteries",
  "Valve of coronary sinus": "rightAtrium",
  "Valve of inferior vena cava": "rightAtrium",
  "Wall of bulb of aorta": "ascendingAorta",
  "Wall of inflow part of right ventricle": "rightVentricle",
  "Wall of left auricle": "leftAuricle",
  "Wall of outflow part of right ventricle": "rightVentricle",
  "Wall of right auricle proper": "rightAuricle",
};

// Structures built entirely (or partly) from real BodyParts3D geometry.
// "myocardium" structures are the ones cutaway/X-ray mode treats as the
// outer wall to hide/fade so internal anatomy becomes visible.
export const MYOCARDIUM_IDS = new Set([
  "rightAtrium",
  "leftAtrium",
  "rightVentricle",
  "leftVentricle",
  "rightAuricle",
  "leftAuricle",
]);

// Structures this app builds procedurally because the source dataset does
// not include them (the great-vessel trunks beyond their roots, and the
// mitral leaflets / some valve cusps / chordae tendineae, which are too
// fine to have been segmented in the source scan).
export const PROCEDURAL_IDS = new Set([
  "superiorVenaCava",
  "inferiorVenaCava",
  "leftPulmonaryArtery",
  "rightPulmonaryArtery",
  "pulmonaryVeins",
  "aorticArch",
  "brachiocephalicTrunk",
  "leftCommonCarotidArtery",
  "leftSubclavianArtery",
  "chordaeTendineae",
]);
